### ISSUE TITLE
Project Status / Next Steps / Roadmap

### ISSUE THREAD

**Issue by mjauernig** [DbUp/DbUp#747]
# Project Status / Next Steps / Roadmap
Today @droyad and I had a zoom call and discussed about DbUp and the future. 

I'm glad that @droyad will become active again and try to find some hours to lead and support the project.

We agreed on the following procedure. @droyad Please correct if misrepresented.

- [ ] Monorepository. Reintegrate the redshift repo.
- [x] Sort the issues.
- [ ] Get rid of all the open issues
- [ ] Update the build pipeline.
- [ ] Creating another v5 release in a few days.
- [ ] Make a v6 release in a few weeks. 
- [ ] Write better documentation and best practice recommendations based on our experience.
- [ ] Write better documentation on how to contribute and create some guidelines.
- [ ] Try to find maintainers for each database.

# Monorepository
We are trying to stay on one repository. I was concerned that we might solve the problem of different development speeds on the different databases. But on the contrary, we will get a different state of features which will be hard to maintain.

# Sorting the issues 
Create a GitHub project and sort out all the issues. This should be the basis for prioritizing and getting rid of all open issues.
I created the project [Issue sorting](https://github.com/orgs/DbUp/projects/5/views/1) and finished sorting. I create the following column (the order of the list is also the order I suggest to work on it).
- **Build Pipeline**: Everything which is related to github/nuget/readthedocs. I will take care of these issues.
- **Documentation**: I will update the documentation on a first pass. 
- **v5**: Issues / Pull Requests which should be easy to integrate into the existing codebase.
- **v6**: Issues / Pull Requests which are _breaking_ but already accepted.
- **Bugs**: Everything is up-for-grabs. If you have time, check if this is still relevant, write a fix and/or documentation.
- **Backlog**: Everything is up-for-grabs. If you have time, check if it is still relevant, write an implementation and/or documentation.
- **Pull requests to check**: Everything is up-for-grap. If you have time, check if they are still relevant.
- **Whishlist - Naming scripts**: Lots of issues on this topic. After the points above, have an open discussion if and how we should implement it.
- **Whishlist**: We will look at this after the other work is done.

**Comment by droyad** [comment]
> Monorepository. Reintegrate the redshift repo.
👍 


I'd say more single repo at the moment (i.e a single project), but yes

> Support of .net frameworks and databases

I'd frame it as we'll support .NET 6,7,8. Attempt for .NET Standard 2.0 (which includes `4.6.1`) as long as it doesn't make things too much more complicated.

Also the latest C#.

**Comment by droyad** [comment]
Actually, going through the issues I'm back on the side of repo per provider. I've re-opened #431 so that we can discuss.

**Comment by droyad** [comment]
I've gotten some time to split out all the repos, and that is all done 🎉.

My next focus will be on:
- Setting up contributor guidelines, repository rules and reviewing the contributor list
- The next major breaking version, v6.0. I've picked what I feel at the highest priority and/or reduce cognitive load. They are tagged them with the 6.0.0 milestone.
    - Drop support for older .NET versions
    - Replace LibLog (I see there are PRs already)
    - Replace the Cake build
    - Cleanup Tests and test frameworks used
    - Use new C# features (e.g. file scoped namespaces

The plan is to do `core` first and then sweep through all the providers.

**Comment by droyad** [comment]
#786 is about ready, going to let it steep for a while and get onto the other providers

Once that's all out the door, we'll look at the rest of the backlog.

**Comment by christophwille** [comment]
> steep for a while

I wanted to check in regarding v6 - did it simmer for long enough?

**Comment by droyad** [comment]
I didn't realise there was not beta of the SQL Server provider, so I've pushed that out now. Going to dogfood it this week. Will also work on getting betas out of the other providers.

The MySQL one has been out for a while already.

**Comment by droyad** [comment]
The last big thing left on the core project to do is figure out what to do with https://github.com/DbUp/DbUp/pull/440

**Comment by christophwille** [comment]
Any update on v6?

**Comment by droyad** [comment]
dbup-core 6.0 is shipping!
